src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review (In progress)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window_Template__r.Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Window__c.object
<CustomObject>
    <description>Controls whether a theme is accepting applications</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Application Windows</relationshipLabel>
        <relationshipName>Application_Windows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Window</label>
    <nameField>
        <label>Application Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Windows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Window_Template__c.object
<CustomObject>
    <fields>
        <fullName>Application_Window__c</fullName>
        <label>Application Window</label>
        <referenceTo>Application_Window__c</referenceTo>
        <relationshipLabel>Application Window Templates</relationshipLabel>
        <relationshipName>Application_Window_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SIB_NewApplicationController.cls
public with sharing class SIB_NewApplicationController {
    public String selectedTheme{get;set;}
    public List<String> themes {get;set;}
    public Map<String, Id> themeNameToIdMap{get;set;}
    
    public SIB_NewApplicationController() {
        themeNameToIdMap = new Map<String, Id>();
        themes = new List<String>();
        for(Theme__c theme : [
            SELECT Name, Id
            FROM Theme__c
        ]){
            themeNameToIdMap.put(theme.Name, theme.Id);
            themes.add(theme.Name);
        }
    }

    public void setValue(){
        selectedTheme = EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('valueToSet'), 'UTF-8');
    }

    public PageReference startApplication(){
        Application_Window__c applicationWindow = null;
        List<Application_Window__c> appWindows = [
            SELECT Id, Is_Live__c, Start_Date__c, (
                SELECT Id
                FROM Application_Window_Templates__r
            )
            FROM Application_Window__c
            WHERE Theme__c = :selectedTheme
            ORDER BY End_Date__c ASC
        ];
        for(Application_Window__c applicationWindowToCheck : appWindows){
            applicationWindow = applicationWindowToCheck;
            if(applicationWindowToCheck.Is_Live__c || applicationWindowToCheck.Start_Date__c > Date.today()){
                break;
            }
        }
        List<Contact> contactRecords = Database.query('SELECT Id FROM Contact WHERE Email = \'' + UserInfo.getUserEmail() + '\'');
        Application__c applicationToCreate = new Application__c(
            Application_Window_Template__c = applicationWindow.Application_Window_Templates__r[0].Id,
            Status__c = 'Draft',
            Contact__c = contactRecords.isEmpty() ? null : contactRecords[0].Id
        );
        insert applicationToCreate;
        return new PageReference('/apex/SIB_ApplicationForm?id=' + applicationToCreate.Id + '&formType=Expression%20Of%20Interest');
    }

    public PageReference checkLoggedInStatus(){
        return SIB_Utilities.checkLoggedInStatus();
    }
}