src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Expression of Interest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Full Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Project</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dev_Form_External_Status__c</fullName>
        <formula>IF(
   OR(
      TEXT(Development_Form_Status__c) = &quot;Under Review&quot;, 
      TEXT(Development_Form_Status__c) = &quot;Ready for Approval&quot;
   ), &quot;Submitted&quot;, TEXT(Development_Form_Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dev Form External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOI_External_Status__c</fullName>
        <formula>IF(
   OR(
      TEXT(Status__c) = &quot;Under Review&quot;, 
      TEXT(Status__c) = &quot;Ready for Approval&quot;
   ), &quot;Submitted&quot;, TEXT(Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EOI External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review (In progress)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window_Template__r.Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SIB_ApplicationListController.cls
public with sharing class SIB_ApplicationListController {
    //As with all the pages where we require a user to be logged in, we check here if the user is logged in, else return the homepage
	public PageReference checkLoggedInStatus(){
        return SIB_Utilities.checkLoggedInStatus();
    }
    /*
        This method returns all applications. Because of how security is set up and the "with sharing" setting, 
        we dont need to worry about hiding other applications from other users.
    */
    public List<Application__c> getApplications(){
    	return [
    		SELECT Id, Status__c, Theme__c, Application_Stage__c, Name, 
            EOI_External_Status__c, Dev_Form_External_Status__c, Full_Application_External_Status__c, Identity_Check_External_Status__c
    		FROM Application__c
            ORDER BY Theme__c
    	];
    }
}