src/objects/Application_Question__c.object
<CustomObject>
    <fields>
        <fullName>Field_From_Contact_Record__c</fullName>
        <description>This is the API name of the field on the contact record you wish to pull the value from.</description>
        <inlineHelpText>This is the API name of the field on the contact record you wish to pull the value from.</inlineHelpText>
        <label>Field From Contact Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Set_On_Answer__c</fullName>
        <label>Field To Set On Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Short_Text_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkboxes_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi_Picklist_Answers__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text_Answer__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Question_Template__c.object
<CustomObject>
    <fields>
        <fullName>Application_Question__c</fullName>
        <label>Application Question</label>
        <referenceTo>Application_Question__c</referenceTo>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Question Template</label>
    <nameField>
        <displayFormat>AQT-{00000}</displayFormat>
        <label>Application Question Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SIB_Utilities.cls
public with sharing class SIB_Utilities {
	public static Map<String, Map<String, Id>> recordTypeIdCache = new Map<String, Map<String, Id>>();

	public static Boolean isValidEmail(String email) {
		String emailRegex = '^[a-zA-Z0-9\\.\\!\\#\\$\\%\\&\\*\\/\\=\\?\\^\\_\\+\\-\\`\\{\\|\\}\\~\'._%+-]+@[a-zA-Z0-9\\-.-]+\\.[a-zA-Z]+';
		Pattern myPattern = Pattern.compile(emailRegex);
		Matcher myMatcher = myPattern.matcher(email);
		return myMatcher.matches();
	}

	public static String generateDefaultFields(Id applicationWindowTemplateId){
		String fieldsToReturn = '';
		for(Application_Question_Template__c singleQuestionTemplate : [
			SELECT Application_Question__r.Field_From_Contact_Record__c, Application_Question__r.Field_To_Set_On_Answer__c
			FROM Application_Question_Template__c
			WHERE Application_Window_Template__r.Id = :applicationWindowTemplateId
			ORDER BY CreatedDate ASC
		]){
			if(String.isNotBlank(singleQuestionTemplate.Application_Question__r.Field_From_Contact_Record__c)){
				fieldsToReturn = fieldsToReturn + singleQuestionTemplate.Application_Question__r.Field_From_Contact_Record__c + ',';
			}
		}
		fieldsToReturn = fieldsToReturn + 'Id';
		return fieldsToReturn;
	}

	public static Id getRecordTypeId(String objName, String rtName) {
		if(!recordTypeIdCache.containsKey(objName)){
			Map<String, Id> valuesToPut = new Map<String, Id>();
			Map<String,Schema.RecordTypeInfo> recordTypeInfo = Schema.getGlobalDescribe().get(objName).getDescribe().getRecordTypeInfosByName();
			for(String recordTypeInfoName : recordTypeInfo.keySet()){
				valuesToPut.put(recordTypeInfoName, recordTypeInfo.get(recordTypeInfoName).getRecordTypeId());
			}
			recordTypeIdCache.put(objName, valuesToPut);
		}
		return recordTypeIdCache.get(objName).get(rtName);
	}

	public static PageReference checkLoggedInStatus(){
		if(UserInfo.getUserId() == null || UserInfo.getUserName() == 'social_impact_bonds@dev-sibs.cs80.force.com'){
            returnHomePage();
        }
        return null;
	}

	public static PageReference returnHomePage(){
		return new PageReference(Site.getBaseUrl());
	}

	public SIB_Utilities(SIB_ChangePasswordController controller){}
}