src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review (In progress)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window_Template__r.Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Form_Section__c.object
<CustomObject>
    <description>This will hold the help text to allow us to display the user the overview screen.</description>
    <fields>
        <fullName>Form_To_Use_In__c</fullName>
        <label>Form To Use In</label>
        <picklist>
            <picklistValues>
                <fullName>Expression of Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Form</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application Form Section</label>
    <nameField>
        <label>Application Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Form Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Question__c.object
<CustomObject>
    <fields>
        <fullName>Checkboxes_Options__c</fullName>
        <label>Checkboxes Options</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field_From_Contact_Record__c</fullName>
        <description>This is the API name of the field on the contact record you wish to pull the value from.</description>
        <inlineHelpText>This is the API name of the field on the contact record you wish to pull the value from.</inlineHelpText>
        <label>Field From Contact Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Set_On_Answer__c</fullName>
        <label>Field To Set On Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Short_Text_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkboxes_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi_Picklist_Answers__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist_Answer__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text_Answer__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Picklist_Options__c</fullName>
        <label>Picklist Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Short Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Select Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkboxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Checkbox</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Question_Template__c.object
<CustomObject>
    <fields>
        <fullName>Application_Form_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application Form Section</label>
        <referenceTo>Application_Form_Section__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Application_Question_Templates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Question__c</fullName>
        <label>Application Question</label>
        <referenceTo>Application_Question__c</referenceTo>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>Application_Question__r.Question_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question #</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Application Question Template</label>
    <nameField>
        <displayFormat>AQT-{00000}</displayFormat>
        <label>Application Question Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Window__c.object
<CustomObject>
    <description>Controls whether a theme is accepting applications</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Application Windows</relationshipLabel>
        <relationshipName>Application_Windows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Window</label>
    <nameField>
        <label>Application Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Windows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Window_Template__c.object
<CustomObject>
    <fields>
        <fullName>Application_Window__c</fullName>
        <label>Application Window</label>
        <referenceTo>Application_Window__c</referenceTo>
        <relationshipLabel>Application Window Templates</relationshipLabel>
        <relationshipName>Application_Window_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataFactory.cls
@isTest
public class DataFactory {
	public static Theme__c createTheme(String themeName){
		Theme__c themeToCreate = new Theme__c(
			Name = themeName
		);
		return themeToCreate;
	}

	public static Theme__c insertTheme(String themeName){
		Theme__c themeToInsert = createTheme(themeName);
		insert themeToInsert;
		return themeToInsert;
	}

	public static Application_Window__c createAW(Id themeId){
		Application_Window__c awToCreate = new Application_Window__c(
			Name = 'Test AW',
			Theme__c = themeId,
			Start_Date__c = Date.today().addDays(-10),
			End_Date__c = Date.today().addDays(10),
			Is_Live__c = true
		);
		return awToCreate;
	}

	public static Application_Window__c insertAW(Id themeId){
		Application_Window__c awToInsert = createAW(themeId);
		insert awToInsert;
		return awToInsert;
	}

	public static Application_Window_Template__c createAWT(Id awId){
		Application_Window_Template__c awtToCreate = new Application_Window_Template__c(
			Application_Window__c = awId
		);
		return awtToCreate;
	}

	public static Application_Window_Template__c insertAWT(Id awId){
		Application_Window_Template__c awtToInsert = createAWT(awId);
		insert awtToInsert;
		return awtToInsert;
	}

	public static Application_Form_Section__c createAFS(String name, String formToUseIn){
		Application_Form_Section__c afsToCreate = new Application_Form_Section__c(
			Name = name,
			Form_To_Use_In__c = formToUseIn
		);
		return afsToCreate;
	}

	public static Application_Form_Section__c insertAFS(String name, String formToUseIn){
		Application_Form_Section__c afsToInsert = createAFS(name, formToUseIn);
		insert afsToInsert;
		return afsToInsert;
	}

	public static Application_Question__c createAQ(String contactRecordField, String fieldToSetOnAnswer){
		Application_Question__c aq = new Application_Question__c(
			Name = 'First Name',
			Field_From_Contact_Record__c = contactRecordField,
			Field_To_Set_On_Answer__c = fieldToSetOnAnswer,
			Question__c = 'First Name',
			Question_Type__c = 'Short Text',
			Picklist_Options__c = 'Test;Test2;Test3;',
			Checkboxes_Options__c = 'Test;Test2;Test3;',
			Required__c = true
		);
		return aq;
	}

	public static Application_Question__c insertAQ(String contactRecordField, String fieldToSetOnAnswer){
		Application_Question__c aq = createAQ(contactRecordField, fieldToSetOnAnswer);
		insert aq;
		return aq;
	}

	public static Application_Question_Template__c createAQT(Id awId, Id aqId, Id afsId){
		Application_Question_Template__c aqtToCreate = new Application_Question_Template__c(
			Application_Question__c = aqId,
			Application_Window_Template__c = awId,
			Application_Form_Section__c = afsId
		);
		return aqtToCreate;
	}

	public static Application_Question_Template__c insertAQT(Id awId, Id aqId, Id afsId){
		Application_Question_Template__c aqtToInsert = createAQT(awId, aqId, afsId);
		insert aqtToInsert;
		return aqtToInsert;
	}

	public static Contact createContact(String contactEmail){
		Contact contactToCreate = new Contact(
			LastName = 'Test',
			Email = contactEmail
		);
		return contactToCreate;
	}

	public static Contact insertContact(String contactEmail){
		Contact contactToInsert = createContact(contactEmail);
		insert contactToInsert;
		return contactToInsert;
	}

	public static Application__c createApplication(Id awtId, Id contactId, String status){
		Application__c appToCreate = new Application__c(
			Application_Window_Template__c = awtId,
			Contact__c = contactId,
			Status__c = status
		);
		return appToCreate;
	}

	public static Application__c insertApplication(Id awtId, Id contactId, String status){
		Application__c appToInsert = createApplication(awtId, contactId, status);
		insert appToInsert;
		return appToInsert;
	}
}